### ISSUE TITLE
petstore-full not starting

### ISSUE THREAD

**Issue by mchampine** [cognitect-labs/vase#31]
# Description

lein run in petstore-full example throws exception on start

petstore-full $ lein run
WARNING: seqable? already refers to: #'clojure.core/seqable? in namespace: clojure.core.incubator, being replaced by: #'clojure.core.incubator/seqable?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer.utils, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: boolean? already refers to: #'clojure.core/boolean? in namespace: clojure.tools.analyzer, being replaced by: #'clojure.tools.analyzer.utils/boolean?
WARNING: bounded-count already refers to: #'clojure.core/bounded-count in namespace: clojure.core.async, being replaced by: #'clojure.core.async/bounded-count
INFO  datomic.kv-cluster - {:event :kv-cluster/retry, :StorageGetBackoffMsec 0, :attempts 0, :max-retries 20, :cause "java.net.ConnectException", :pid 34127, :tid 13}
INFO  datomic.kv-cluster - {:event :kv-cluster/retry, :StorageGetBackoffMsec 50, :attempts 1, :max-retries 20, :cause "java.net.ConnectException", :pid 34127, :tid 13}
INFO  datomic.kv-cluster - {:event :kv-cluster/retry, :StorageGetBackoffMsec 100, :attempts 2, :max-retries 20, :cause "java.net.ConnectException", :pid 34127, :tid 13}
INFO  datomic.kv-cluster - {:event :kv-cluster/retry, :StorageGetBackoffMsec 150, :attempts 3, :max-retries 20, :cause "java.net.ConnectException", :pid 34127, :tid 13}
INFO  datomic.kv-cluster - {:event :kv-cluster/retry, :StorageGetBackoffMsec 200, :attempts 4, :max-retries 20, :cause "java.net.ConnectException", :pid 34127, :tid 13}
INFO  datomic.kv-cluster - {:event :kv-cluster/retry, :StorageGetBackoffMsec 250, :attempts 5, :max-retries 20, :cause "java.net.ConnectException", :pid 34127, :tid 13}
INFO  datomic.kv-cluster - {:event :kv-cluster/retry, :StorageGetBackoffMsec 300, :attempts 6, :max-retries 20, :cause "java.net.ConnectException", :pid 34127, :tid 13}
Exception in thread "main" java.util.concurrent.ExecutionException: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: localhost:4335" [90067-171], compiling:(petstore_full/server.clj:7:1)
	at clojure.lang.Compiler.load(Compiler.java:7441)
	at clojure.lang.RT.loadResourceScript(RT.java:374)
	at clojure.lang.RT.loadResourceScript(RT.java:365)
	at clojure.lang.RT.load(RT.java:455)
	at clojure.lang.RT.load(RT.java:421)
	at clojure.core$load$fn__7840.invoke(core.clj:6008)
	at clojure.core$load.invokeStatic(core.clj:6007)
	at clojure.core$load.doInvoke(core.clj:5991)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5812)
	at clojure.core$load_one.invoke(core.clj:5807)
	at clojure.core$load_lib$fn__7785.invoke(core.clj:5852)
	at clojure.core$load_lib.invokeStatic(core.clj:5851)
	at clojure.core$load_lib.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5889)
	at clojure.core$load_libs.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5911)
	at clojure.core$require.doInvoke(core.clj:5911)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval15$fn__19.invoke(form-init1832586691876862531.clj:1)
	at user$eval15.invokeStatic(form-init1832586691876862531.clj:1)
	at user$eval15.invoke(form-init1832586691876862531.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6977)
	at clojure.lang.Compiler.eval(Compiler.java:6967)
	at clojure.lang.Compiler.load(Compiler.java:7429)
	at clojure.lang.Compiler.loadFile(Compiler.java:7367)
	at clojure.main$load_script.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invokeStatic(main.clj:279)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invokeStatic(main.clj:310)
	at clojure.main$null_opt.invokeStatic(main.clj:344)
	at clojure.main$null_opt.invoke(main.clj:341)
	at clojure.main$main.invokeStatic(main.clj:423)
	at clojure.main$main.doInvoke(main.clj:386)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.util.concurrent.ExecutionException: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: localhost:4335" [90067-171]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at clojure.core$deref_future.invokeStatic(core.clj:2290)
	at clojure.core$future_call$reify__9371.deref(core.clj:6847)
	at clojure.core$deref.invokeStatic(core.clj:2310)
	at clojure.core$deref.invoke(core.clj:2296)
	at datomic.coordination$lookup_transactor_endpoint$fn__5161.invoke(coordination.clj:132)
	at datomic.coordination$lookup_transactor_endpoint.invokeStatic(coordination.clj:130)
	at datomic.coordination$lookup_transactor_endpoint.invoke(coordination.clj:127)
	at datomic.coordination$lookup_compatible_transactor_endpoint.invokeStatic(coordination.clj:148)
	at datomic.coordination$lookup_compatible_transactor_endpoint.invoke(coordination.clj:146)
	at datomic.peer$send_admin_request$fn__8304.invoke(peer.clj:759)
	at datomic.peer$send_admin_request.invokeStatic(peer.clj:753)
	at datomic.peer$send_admin_request.invoke(peer.clj:751)
	at datomic.peer$create_database.invokeStatic(peer.clj:773)
	at datomic.peer$create_database.invoke(peer.clj:763)
	at datomic.peer$create_database.invokeStatic(peer.clj:765)
	at datomic.peer$create_database.invoke(peer.clj:763)
	at clojure.lang.Var.invoke(Var.java:379)
	at datomic.Peer.createDatabase(Peer.java:117)
	at datomic.api$create_database.invokeStatic(api.clj:19)
	at datomic.api$create_database.invoke(api.clj:17)
	at com.cognitect.vase.datomic$connect.invokeStatic(datomic.clj:13)
	at com.cognitect.vase.datomic$connect.invoke(datomic.clj:9)
	at com.cognitect.vase$ensure_schema$fn__14531.invoke(vase.clj:45)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__9124.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__9124.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__9066$G__9061__9079.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6704)
	at clojure.core$reduce.invoke(core.clj:6686)
	at com.cognitect.vase$ensure_schema.invokeStatic(vase.clj:44)
	at com.cognitect.vase$ensure_schema.invoke(vase.clj:26)
	at petstore_full.service$service.invokeStatic(service.clj:53)
	at petstore_full.service$service.invoke(service.clj:49)
	at petstore_full.server$eval14649.invokeStatic(server.clj:7)
	at petstore_full.server$eval14649.invoke(server.clj:7)
	at clojure.lang.Compiler.eval(Compiler.java:6977)
	at clojure.lang.Compiler.load(Compiler.java:7429)
	... 40 more
Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused: localhost:4335" [90067-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:158)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:399)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:287)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:109)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:266)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:175)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:684)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:616)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:479)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:135)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:114)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:101)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:125)
	at datomic.sql$connect.invokeStatic(sql.clj:16)
	at datomic.sql$connect.invoke(sql.clj:13)
	at datomic.sql$select.invokeStatic(sql.clj:77)
	at datomic.sql$select.invoke(sql.clj:75)
	at datomic.kv_sql.KVSql.get(kv_sql.clj:60)
	at datomic.kv_cluster.KVCluster$fn__3396$fn__3399$fn__3400.invoke(kv_cluster.clj:226)
	at datomic.kv_cluster$retry_fn$fn__3312.invoke(kv_cluster.clj:82)
	at datomic.kv_cluster$retry_fn.invokeStatic(kv_cluster.clj:82)
	at datomic.kv_cluster$retry_fn.invoke(kv_cluster.clj:57)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:663)
	at clojure.core$partial$fn__6855.doInvoke(core.clj:2616)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at datomic.kv_cluster.KVCluster$fn__3396$fn__3399.invoke(kv_cluster.clj:224)
	at datomic.kv_cluster.KVCluster$fn__3396.invoke(kv_cluster.clj:222)
	at clojure.core$binding_conveyor_fn$fn__6766.invoke(core.clj:2020)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:119)
	at org.h2.util.NetUtils.createSocket(NetUtils.java:100)
	at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:93)
	at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:395)
	... 35 more

## Operating System (including version).

os x 10.9.5

## Your current Leiningen/Boot/Maven version (`lein --version`)

Leiningen 2.7.1 on Java 1.8.0_40 Java HotSpot(TM) 64-Bit Server VM

## Pedestal and Vase version

from petstore-full project.clj

**Comment by ohpauleez** [comment]
For the time being, I would focus more on the `omnext-todo` application.  The `petstore` sample has existed through three major version of Vase (so it borrows "styles" from each version).

We'll get the sample up and running again.

**Comment by mtnygard** [comment]
The exception means that Datomic is not running. Even with Datomic free, you have to start a transactor before running the app.
